direction: down

classes: {
  module: {
    style: {
      border-radius: 5
    }
  }
}

application: Application (Supervised) {
  style: {
    border-radius: 10
  }

  worker-supervisor: Worker Supervisor {
    class: module
  }

  worker: Worker {
    class: module
    style: {
      multiple: true
    }
  }

  controller: Controller {
    class: module
  }

  appstate: State {
    class: module
  }

  web: Web Interface {
    class: module
  }

  controller -> worker-supervisor: Starts workers
  worker-supervisor -> worker: Starts
  worker -> appstate: Publish results
  web <- appstate: Poll results
}

