direction: down

classes: {
  module: {
    style: {
      border-radius: 5
    }
  }
}

internet: Endpoint {
  icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
}

application: Application (Supervised) {
  style: {
    border-radius: 10
  }

  worker-supervisor: Worker Supervisor {
    class: module
  }

  worker: Worker {
    class: module
    style: {
      multiple: true
    }
  }

  controller: Controller {
    class: module
  }

  orch: Orchestrator {
    class: module
  }

  web: Web Interface {
    class: module
  }

  controller -> worker-supervisor: Starts workers
  worker-supervisor -> worker: Starts
  worker -> orch: Publish results
  orch -> controller: Start blasting
  web -> orch: Manage application state
}

  you: You {
    icon: https://icons.terrastruct.com/essentials%2F365-user.svg
  }

application.worker -> internet: Send requests
you -> application.web: Interacts with blast

